spring:
  datasource:
    # https://devcenter.heroku.com/articles/connecting-to-relational-databases-on-heroku-with-java#using-the-jdbc_database_url
    url: ${JDBC_DATABASE_URL}

logging:
  level:
    ROOT: INFO